version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

commands:
  npm-build:
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths: ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: NPM Build
          command: npm run build

jobs:
  build:
    executor: node-executor
    working_directory: ~/project
    steps:
      - npm-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --dir=build
  release:
    executor: node-executor
    working_directory: ~/project
    steps:
      - npm-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --prod --dir=build

workflows:
    build-deploy:
      jobs:
        - build:
            filters:
              branches:
                ignore:
                  - master
        - release:
            filters:
              branches:
                only:
                  - master
